### ISSUE TITLE
JUEGOS XROM

### ISSUE THREAD

**Issue by wilco2009** [RW-FPGA-devel-Team/Videopac-G7000#1]
PENDIENTE IMPLEMENTAR JUEGOS CON PAGINACION MODO XROM.
ROMOE = !(EXTRAM*P11)*PSEN
Juegos:
CRC32=3BFEF56B (4 In 1 Row)
CRC32=9B5E9356 (4 In 1 Row French version)
CRC32=AFB23F89 (Musician)

**Comment by rampa069** [comment]
Hecho! conseguido en el commit 556e822fcc53557b55f5d1dc43ed957aada2288e
