### ISSUE TITLE
vp_28 (volleyball) 

### ISSUE THREAD

**Issue by rampa069** [RW-FPGA-devel-Team/Videopac-G7000#4]
a la hora de hacer el saque de la bola para el inicio del nuevo punto en juego, el core no te deja alcanzar la bola (o no lee bien el joystick, no lo puedo asegurar)

**Comment by G7200** [comment]
Hhmm, looks like it's an overall issue, even on MAME. The 2nd player cannot serve the ball, pressing the fire button won't work.

**Comment by avlixa** [comment]
Bug ya resuelto en rama zxdos.  Es un problema de colisiones, parece que el videopac real tiene un ligero retraso en los objetos minor para detectar la colisión que permite que detecte colisión entre  objetos estando rozando pero si solapar.

**Comment by rampa069** [comment]
confirmed and fixed
