### ISSUE TITLE
General sound chopping

### ISSUE THREAD

**Issue by G7200** [RW-FPGA-devel-Team/Videopac-G7000#7]
There is a hearable chopping in the sound, You can hear it on longer sounds for example in Tutnakhan during the intro music with the pyramid. It's like it's time dependent,  that chopping noise always appear in the same tempo.
Otherwise pulse or square sound and noise does sound very near to the original hardware!

**Comment by rampa069** [comment]
Hi, are you in "Videopac" mode? the tutankamon rom is a prototype (not released) only int3ended for the european console.

**Comment by G7200** [comment]
Hi, I mentioned the game "Tutankhan" just as an example to hear the sound
well. I know it's a prototype. I think this chopping issue is generally on
every game, also in the "SELECT GAME".

Ramon Martinez <notifications@github.com> schrieb am So., 31. Jan. 2021,
02:05:

**Comment by rampa069** [comment]
hello, yes, you are right. it has to be with another issue.  This game, (is the same in frogger) is not using the standard audio registers. It writes direct to A11 of the chip :-(  investigating.

**Comment by G7200** [comment]
ok, yeah but on frogger the sound is on the console itself choppy as well.

Ramon Martinez <notifications@github.com> schrieb am So., 31. Jan. 2021,
10:35:

**Comment by G7200** [comment]
I just checked my PAL Tutankhan and on there, the intro sound melody is
very clean, no choppyness at all.

Ramon Martinez <notifications@github.com> schrieb am So., 31. Jan. 2021,
10:35:

**Comment by rampa069** [comment]
you were right. Spotted and fixed.....

Can you please test this beta and confirm?
(btw, looking at your nick, i think you are going to be very happy with the "new" OSD option.... :-)

[mister-beta.zip](https://github.com/RW-FPGA-devel-Team/Videopac-G7000/files/5901390/mister-beta.zip)

**Comment by G7200** [comment]
Thanks for the beta.
Sound is now spot on!
Well done!

Ramon Martinez <notifications@github.com> schrieb am Mo., 1. Feb. 2021,
02:50:

**Comment by rampa069** [comment]
closed. seems this one is fixed
